apiVersion: v1
kind: NodePort
metadata:
  name: test-service
  namespace: test-app
spec:
  selector:
    app: test
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080