apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: test-app
spec:
  selector:
    app: test
  ports:
    - name: http
      protocol: TCP
      port: 4421
      targetPort: 4421
  type: NodePort